update »Scala Maven Plugin« to fix build error on generating Java source(s)
With »Scala Maven Plugin« version 3.3.1 the build fails on random
machines with:
```
[INFO]
------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Vavr Parent 1.0.0-SNAPSHOT ......................... SUCCESS [0.277 s]
[INFO] Vavr Match ......................................... SUCCESS [1.478 s]
[INFO] Vavr ............................................... FAILURE [9.971 s]
[INFO] Vavr Benchmark ..................................... SKIPPED
[INFO] Vavr Test 1.0.0-SNAPSHOT ........................... SKIPPED
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 12.025 s
[INFO] Finished at: 2018-07-28T12:21:27+02:00
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:script (default) on project vavr: wrap: java.lang.Exception: A NoSuchMethodError exception was thrown: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object; -> [Help 1]
```

After update to recent version 3.4.1 of the plugin the build finishes
successfully.

Fixes #2269.